### ISSUE TITLE
Add Javadoc to Data Classes

### ISSUE THREAD

**Issue by JannikEmmerich** [cryptic-game/java-backend-dev#31]
**Is your feature request related to a problem? Please describe.**

Currently there is no documentation for the data classes.

**Describe the solution you'd like**

Add javadoc to every data class.

**Additional Comments**

For some examples look into data classes with existing javadoc

**Comment by cephox** [comment]
Da sind noch mehr commits, sry hab vergessen die Nummer des Issues in die Message zu schreiben
