### ISSUE TITLE
Add Network Endpoints

### ISSUE THREAD

**Issue by JannikEmmerich** [cryptic-game/java-backend-dev#32]
**Describe the solution you'd like**
Add network endpoints so that the new Java backend has the same state as the old one.

**Additional Comments**
You can find the endpoints in the [old backend](https://github.com/cryptic-game/cryptic-network/tree/experimental).

**Assigness**
[NetworkEndpoint.java](https://github.com/cryptic-game/cryptic-network/blob/experimental/src/main/java/net/cryptic_game/microservice/network/endpoint/NetworkEndpoint.java) @msentwickler
[NetworkMemberEndpoint.java](https://github.com/cryptic-game/cryptic-network/blob/experimental/src/main/java/net/cryptic_game/microservice/network/endpoint/NetworkMemberEndpoint.java) @Fuam5 
[NetworkOwnerEndpoint.java](https://github.com/cryptic-game/cryptic-network/blob/experimental/src/main/java/net/cryptic_game/microservice/network/endpoint/NetworkOwnerEndpoint.java) @msentwickler

**Comment by JannikEmmerich** [comment]
Test https://github.com/cryptic-game/cryptic-network/tree/experimental

**Comment by MarcelCoding** [comment]
@joduction please write your name `@joduction` behind the name of the file you are editing.

**Comment by Fuam5** [comment]
I shoud write a Comment

**Comment by Cr7mbl3** [comment]
I want to be assigned

**Comment by msentwickler** [comment]
I would do the two other tasks
